[Interface]
PrivateKey = yJ78dqni/qxNCY94hlGFYiGwPxZ7LF9UfsYDTbOtUWc=
Address = 100.64.0.2/32, fd00:64::c0a:5ee8:5aac:62a/128
DNS = 100.64.0.1
MTU = 1420

[Peer]
PublicKey = KRnXAmP1U86vJ2pZUxLgP9JzQ8aRN8xdV5RNk4AGgyY=
Endpoint = 127.0.0.1:51820
AllowedIPs = 0.0.0.0/0, ::/0
PresharedKey = FRc++QT+GYarNBOnwHfAAra82Z2p/3VY1/ivHB+32sc=