[Interface]
PrivateKey = UA4Knyt7NGyDrnhEgoAxgT+MhzCSHrx5OUfHEhLj1Xo=
Address = 100.64.0.2/32, fd00:64::93e8:2c7f:1d0e:b5e5/128
DNS = 100.64.0.1
MTU = 1420

[Peer]
PublicKey = siW/5AZ48Po8CocEKkHo3m/9NlZgsGLN+b1aOIRiqDI=
Endpoint = 192.168.86.18:51820
AllowedIPs = 0.0.0.0/0, ::/0
PresharedKey = b8janKSuln8x4dMJaRLg6DhzzYbe7I6bBMa3oN67fNc=
